### ISSUE TITLE
Java example

### ISSUE THREAD

**Issue by kovacserik** [modheader/modheader_selenium#12]
Do you have an example for Selenium-Java?

**Comment by anthonybaldwin** [comment]
Hope this helps!

```    
        ChromeOptions options = new ChromeOptions();
        options.addExtensions(new File("modheader.crx"));
     
        Map<String,String> headers;
        headers = new HashMap<String,String>();

        if ( youWantHeaders )
        {
            headers.put("header1","value1");
        }
        
        if ( youWantAnotherHeader )
        {
            headers.put("header2","value2");
        }

        //Using headers above, generate API request for modheader_selenium
        if ( headers.size() > 0 )
        {
            String headerList = "";
            //generate list using all headers in map:
            // {name1}={value1}&{name2}={value2}&
            for (Map.Entry<String,String> header : headers.entrySet()) {
                headerList += header.getKey() + '=' + header.getValue() + '&';
            }
            //add headers
            driver.get("https://bewisse.com/add?" + headerList);
        }
        return driver;

**Comment by anthonybaldwin** [comment]
Note: It appears the domain has changed to `webdriver.bewisse.com` with the most recent crx. I need to update. :)

**Comment by kovacserik** [comment]
Can you please specify driver.get("https://webdriver.bewisse.com/add?" + headerList); this line?

It's working in my example(woooow!!!) , I just want to know why that line is necessary 

Thanks

**Comment by anthonybaldwin** [comment]
It's the "API" which updates the header. These files: https://github.com/bewisse/modheader_selenium/tree/master/modheader

I haven't played with using the files locally, but need to... I'm sure can just hit a local `add.html` instead.

Also oddly enough https://bewisse.com/add (and [add.html](https://bewisse.com/add.html)) appears to be live but https://webdriver.bewisse.com/add (nor [add.html](https://webdriver.bewisse.com/add.html)) does not. Not sure why. I only mentioned the change because of [this commit](https://github.com/bewisse/modheader_selenium/commit/86f8a7b91f0059b3706b148ee6a1b5ef251dcde3).

**Comment by mideep1990** [comment]
For me this line **driver.get("https://webdriver.bewisse.com/add?" + headerList);** is saying this site can not be reached...

**Comment by anthonybaldwin** [comment]
Oh, I was assuming from the change made [here to the README.md](https://github.com/bewisse/modheader_selenium/commit/86f8a7b91f0059b3706b148ee6a1b5ef251dcde3#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) that you should be adding the `webdriver` subdomain. Try removing that to see if it helps.

**Comment by hao1300** [comment]
Thanks for the information here. I have updated the README to include instructions for Java, and also include examples here: https://github.com/modheader/modheader_selenium/tree/main/examples/javawebdriver
