### ISSUE TITLE
ModHeader makes Selenium detected by Cloudflare

### ISSUE THREAD

**Issue by anhhung4u** [modheader/modheader_selenium#30]
I run my code without mod Header and it passed Cloudflare https://nowsecure.nl, but when I add modHeader extension to Chrome (with/without changing header), it makes Cloudeflare detect Selenium immediately.

I've tested many times and many case, and I guess because of Mod Header changes navigator.plugins so it make Cloudflare detects Selenium
Before adding ModHeader to Chrome
https://i.imgur.com/ZdVgMNH.png
After adding ModHeader to Chrome
https://i.imgur.com/vJoZFFJ.png

**Comment by hao1300** [comment]
@anhhung4u - there are 3 blackboxes here - CloudFlare, Selenium, and Chrome. I am not sure what you are trying to do, or how to help you with this, but here is what I would suggest:
1, Try using Selenium with Firefox. See if this issue is specific to the Chrome browser.
2, Try to install other extensions in Chrome selenium. See if other extensions also cause CloudFlare to detect it
3, Rebuild ModHeader selenium (https://github.com/modheader/modheader_selenium/tree/main/modheader) by stripping out everything, then slowly add things back until it gets detected by CloudFlare. Then you will know which line/configuration causes CloudFlare to detect it.

**Comment by anhhung4u** [comment]
> @anhhung4u - there are 3 blackboxes here - CloudFlare, Selenium, and Chrome. I am not sure what you are trying to do, or how to help you with this, but here is what I would suggest: 1, Try using Selenium with Firefox. See if this issue is specific to the Chrome browser. 2, Try to install other extensions in Chrome selenium. See if other extensions also cause CloudFlare to detect it 3, Rebuild ModHeader selenium (https://github.com/modheader/modheader_selenium/tree/main/modheader) by stripping out everything, then slowly add things back until it gets detected by CloudFlare. Then you will know which line/configuration causes CloudFlare to detect it.

Thank you for fast response, 
I've tested case 2: try to install other extensions in Chrome Selenium, everything is good, not detected by Cloudflare, so I think it's caused by Mod Header.
I will try to test case 1 and case 3 then update in this post later

**Comment by hao1300** [comment]
Closing since there is no activities.
