### ISSUE TITLE
Headless mode doesnt work but non headless is fine

### ISSUE THREAD

**Issue by kpokala** [modheader/modheader_selenium#41]
I am trying headless mode and non headless is fine for me. But I need to run in headless for my piplelie. I used the following code to run
Path currentRelativePath = Paths.get("mods/ModHeader.crx");
ChromeOptions options = new ChromeOptions();
options.addExtensions(new File(currentRelativePath.toAbsolutePath().toString()));

         options.addArguments("--headless=chrome");
         ChromeDriver driver = new ChromeDriver(options);
         driver.get("https://chrome.google.com/webstore/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj");
         driver.get("https://webdriver.modheader.com/add?keys=user");
         Thread.sleep(5000);
where I need to add keys = user. Its fine on non headless but in healdess it fails and I get the below error

net.serenitybdd.core.exceptions.SerenityManagedException: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: failed to wait for extension background page to load: chrome-extension://jciacimpfapbkckkegdfngcnbdpabaoi/_generated_background_page.html
from unknown error: page could not be found: chrome-extension://jciacimpfapbkckkegdfngcnbdpabaoi/_generated_background_page.html 
Host info: host: 'UK-C02FK7EPML7H', ip: 'fe80:0:0:0:1439:59e7:ffd0:28da%en0'
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6.1', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless=chrome], extensions: [Q3IyNAMAAABBAQAAEqgCCqIBMIG...]}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless=chrome], extensions: [Q3IyNAMAAABBAQAAEqgCCqIBMIG...]}}}]

Did anyone face similar issue. No matter what I do, the line where I instantiate doesnt go beyond that line

**Comment by hao1300** [comment]
Hi @kpokala - can you confirm if my understanding of your issue is correct:
1, Your test works when you remove `--headless=chrome` with the ModHeader selenium extension installed.
2, Your test browser can start with `--headless=chrome` but without the ModHeader selenium extension installed (the test may fail but at least they do not crash).

This sounds like an issue with headless mode + extension installation. What is your Chrome version and Chrome driver version? Make sure they both match. Other than that, I think your best bet would be to post the question on https://groups.google.com/g/chromedriver-users or StackOverflow as this seems like an issue with ChromeDriver rather than ModHeader.

For further diagnosis, can you try installing another extension in your WebDriver in headless mode to see if they would prevent the browser from starting? You can download CRX file for Chrome extensions at chrome-stats.com. If installing other extensions also result in similar crashes, then it is definitely a ChromeDriver issue.

**Comment by kpokala** [comment]
Hi , 

1.yes it works with --headless=chrome  with the ModHeader selenium extension installed.
2.  I didnt try the second one as I need with ModHeaders only.
My Chrome driver versions are 108 or 109 including chrome browsers. Did you mean to say get a different ModHeader crx version for the chrome driver version I am using? is there like a equivalent version for ModHeader for a certain driver

**Comment by hao1300** [comment]
@kpokala

So it was working in non-headless mode with a previous version of ModHeader? Which version of ModHeader was working for you in non-headless mode?

Can you try running --headless=chrome without installing ModHeader extension to see if it starts up the browser successfully? If it does not even start without ModHeader extension, then it is definitely a Chrome headless driver issue. In that case, you will definitely want to ask https://groups.google.com/g/chromedriver-users for helps.

If it *does* start without the ModHeader extension, can you try installing a different extension. For example, something like https://chrome-stats.com/d/jplinlncnelpoehbpiadbcmobgmiempp/download (this is ModLinks, also published by us). This is just to see if the Chrome headless driver *can* start at all with an extension installed. If it also does not start with another extension, that means there is definitely something wrong with Chrome headless driver on your machine that prevents it from installing any extension.

Otherwise, if the headless browser starts with another extension installed, but not with ModHeader extension installed, then there is some issue with the interaction between ModHeader and Chrome headless driver. We will need to do a deeper debugging session in that case.

**Comment by kpokala** [comment]
I tried ModLinks but didnt work. Chrome driver didnt start at all.Got this error
     net.serenitybdd.core.exceptions.SerenityManagedException: org.openqa.selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: headless chrome=109.0.5414.87)
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6.1', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [47a5aa755d2ca5f10fe9f1156490d509, get {url=https://webdriver.modheader.com/add?puid=test%20user%201}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 109.0.5414.87, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: /var/folders/v9/5x952fms0d9...}, goog:chromeOptions: {debuggerAddress: localhost:61972}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: MAC, proxy: Proxy(), se:cdp: ws://localhost:61972/devtoo..., se:cdpVersion: 109.0.5414.87, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}

**Comment by hao1300** [comment]
OK, it is definitely an issue with Chrome / ChromeDriver. Looks like you already found the bug to it. There is nothing we can do on ModHeader side. Please follow up with the Chrome team to figure out a solution.

**Comment by kpokala** [comment]
Thanks but issue is with modheader only for Chrome 109 version. Is the version you have working with Chrome 109/108?

**Comment by hao1300** [comment]
@kpokala - It was working for Chrome 105, and now it does not work in Chrome 109, so there is likely a regression in Chrome some time between Chrome 106-109.

**Comment by karlicoss** [comment]
if someone else runs into the same issue: apparently you need to use `--chrome=new` now :) https://bugs.chromium.org/p/chromium/issues/detail?id=1380881

**Comment by hao1300** [comment]
@karlicoss - Thanks for the tips!
